#!/usr/bin/env python
"""
Script which doubles as serve entrypoint to download code from S3 and start the model server.
"""
import os

from sagemaker_inference import model_server
from sagemaker_training import files, environment

# Download code into container
files.download_and_extract(uri=os.environ['s3_path'], path=environment.code_dir)

# Start the model server
model_server.start_model_server()